### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by legramps** [leryss/LViewLoL#1]
When i tried to run `b2 --with-python link=shared toolset=msvc-14.1 address-model=32 variant=release`, it gave an error
![image](https://user-images.githubusercontent.com/16450539/105057356-194aab80-5ab0-11eb-9ae7-5c2c30915c66.png)
also when compiling the app
![image](https://user-images.githubusercontent.com/16450539/105057450-341d2000-5ab0-11eb-8177-2f848113f10a.png)

**Comment by legramps** [comment]
I used VS 2019 and 2017 and im still getting this issue, any ideas?

**Comment by leryss** [comment]
Did you install python 3.9 for 64 bit ? If so, uninstall it and install the 32 bit version. https://www.python.org/ftp/python/3.9.0/python-3.9.0.exe Don't forget to check Add to PATH

**Comment by legramps** [comment]
thank you! One last thing, after comping, it can't detect the league process and if i run it from the release folder `No height_map.bin file`

**Comment by legramps** [comment]
Okay i fixed it now, thank you so much!

**Comment by Two-Apes** [comment]
Hi @legramps ! Can you tell me how did you fixed the "No height_map.bin" error ?
