### ISSUE TITLE
Offsets need to be updated

### ISSUE THREAD

**Issue by bugra053** [leryss/LViewLoL#13]
Script doesn"t work after new patch offsets need to be updated

**Comment by bckd00r** [comment]
I'll send the new update and performance updates if I'm available tonight.

**Comment by egssy0** [comment]
@bckd00r Don't help this guy, this guy selling lview with LeagueScript name
He known paster on unknowncheats already he's discord Michael Scofield#2021
Don't help this guy

**Comment by bugra053** [comment]
Ne anlatıyorsun birader ne boş yaptın bir şey sattığım falan yok türküm ben

**Comment by bckd00r** [comment]
@egssy0 thanks for informing, you can share discord address?

**Comment by bugra053** [comment]
My brother, what are you talking about? I am Turkish and I don't understand what you are talking about

**Comment by bugra053** [comment]
my discord address Buğra#4486

**Comment by bugra053** [comment]
You talkin 'about a different man it has nothing to do with me

**Comment by bckd00r** [comment]
We do not help sellers in any way, sorry i can't help you i'm closing this issue.

**Comment by bugra053** [comment]
![xxxx](https://user-images.githubusercontent.com/78590908/107122207-5cc25980-68a7-11eb-881d-d670d9a14ccd.png)

**Comment by bugra053** [comment]
i am not a seller and i already updated

**Comment by bugra053** [comment]
I'm not the person you are talking about

**Comment by bckd00r** [comment]
![Screenshot_2021-02-06-18-21-58~2.png](https://user-images.githubusercontent.com/48347237/107122359-5c768e00-68a8-11eb-922a-0ccd4b2c801b.png)

You have verified that you are yourself.

**Comment by egssy0** [comment]
As I say, he selling valolrant too lol

**Comment by bugra053** [comment]
this is different

**Comment by bugra053** [comment]
that is not me

**Comment by egssy0** [comment]
@bugra053 Sorry mate pasters everywhere we can't help you about updating offsets, because we can't verify you

**Comment by bugra053** [comment]
Buğra#4486 my discord adress

**Comment by egssy0** [comment]
+If you updated your source you can close this issue

**Comment by bugra053** [comment]
why do you show me to blame for people I don't know

**Comment by egssy0** [comment]
First of all, your account created today
And Michael Scofield s  real name Bugra,
and Michael scofield not updated he's LeagueScript paste like 2 days because new game update

**Comment by bugra053** [comment]
And Michael Scofield s real name Bugra, really??

**Comment by bugra053** [comment]
![Uploading image.png…]()

**Comment by bugra053** [comment]
![xxxxxx](https://user-images.githubusercontent.com/78590908/107122704-5d102400-68aa-11eb-8f37-9e12a02ac932.png)

**Comment by bugra053** [comment]
I will not provide any more evidence

**Comment by egssy0** [comment]
I don't know what you and he talking about but @bckd00r knows I think.

**Comment by bugra053** [comment]
I'm not the person you describe

**Comment by bckd00r** [comment]
Please discuss it among yourselves. This is not a fighting platform, this is a developer platform.

**Comment by bugra053** [comment]
My goal is for you not to stop developing this program

**Comment by bugra053** [comment]
otherwise I wouldn't try so hard

**Comment by bugra053** [comment]
The program is going very well, evade there are some problems, for example, but it can be improved.

**Comment by bugra053** [comment]
I hope I could explain myself well to you, I am waiting for the new update for evade
