### ISSUE TITLE
Any way i could make this work on garena?

### ISSUE THREAD

**Issue by RiotKassadin** [leryss/LViewLoL#21]
lview doesn't detect garena game client but offsets should be the same

**Comment by legramps** [comment]
Lview does detect garena.

**Comment by RiotKassadin** [comment]
It still says [i] Waiting for league process... even after in game. The server i'm playing in is singapore

**Comment by legramps** [comment]
tried running in admin?

**Comment by RiotKassadin** [comment]
worked, thank you very much. Didn't bother trying it before because it wasn't required on the riot game client
