### ISSUE TITLE
Ingame cursor replaced by default windows cursor

### ISSUE THREAD

**Issue by orkido** [leryss/LViewLoL#3]
[ImGui](https://github.com/leryss/LViewLoL/blob/af7a351b924efa666de8f55c484deda5a80da00f/LView/imgui_impl_win32.cpp#L144) replaces my ingame cursor with the default windows cursor. I created a hacky workaround by adding `WS_EX_TRANSPARENT` [here](https://github.com/leryss/LViewLoL/blob/af7a351b924efa666de8f55c484deda5a80da00f/LView/Overlay.cpp#L34) triggered with a hotkey.
Is this expected behaviour or something specific to my setup?

**Comment by leryss** [comment]
Didn't notice this, you can make a pull request if you want to fix this.
