### ISSUE TITLE
boost::python::error_already_set at memory location

### ISSUE THREAD

**Issue by Gael22601** [leryss/LViewLoL#6]
Hi i have a problem it seems to happen each time i try to enter a game (not the loading screen but the game)
this is the output i get when ending the program:
```
Exception thrown at 0x75AEA842 in ConsoleApplication.exe: Microsoft C++ exception: boost::python::error_already_set at memory location 0x0096DEA0.
Unhandled exception at 0x75AEA842 in ConsoleApplication.exe: Microsoft C++ exception: boost::python::error_already_set at memory location 0x0096DEA0.
```
![image](https://user-images.githubusercontent.com/60848050/105641304-7d3fec00-5e83-11eb-9f1e-6ce2a81b67d2.png)

And this is what i get when i continue:
```
Exception thrown at 0x7911EC70 (python39.dll) in ConsoleApplication.exe: 0xC0000005: Access violation reading location 0xCCCCCCCC.
Unhandled exception at 0x7911EC70 (python39.dll) in ConsoleApplication.exe: 0xC0000005: Access violation reading location 0xCCCCCCCC.
```
![image](https://user-images.githubusercontent.com/60848050/105641463-65b53300-5e84-11eb-90b3-7b12c8d2f3d6.png)

I have followed every steps correctly and it seems to still not work and as I don't understand a thing about programing is there something that is missing?

**Comment by orkido** [comment]
The boost::python::error_already_set exception happens in my setup aswell an it looks like it can be ignored.

Did you configure `::scriptsFolder=` to the correct path in config.ini?

**Comment by Gael22601** [comment]
Looks like that seem to have been the problem i forgot to change the path thanks a lot for your help.
