### ISSUE TITLE
Evade and Advanced Orbwalker

### ISSUE THREAD

**Issue by rundllhan32** [leryss/LViewLoL#7]
Hello, I discovered your application today. I want to state that I found it very successful. I think you are developing it alone. Although it is playable for the moment, there are two issues I would like to request.

The first is the use of skill combined with the orbwalk.  For now, we can only use the skills together with prediction. The ability to use all combos assigned to a single key, like in internal scripts, would be great.

My second wish is for evade to come. I guess I don't need to explain this.

Thanks again for the script. We look forward to your development news and this development roadmap.

**Comment by leryss** [comment]
The development of this project is over, no new features will be added, if you find bugs for the current features feel free to submit am issue. If you wish to have new features you can implement them and make a pull request.
