### ISSUE TITLE
Do I Need to add new python script to somewhere?

### ISSUE THREAD

**Issue by rootcause0** [leryss/LViewLoL#9]
I've created a new python script(Show enemy attack range) for the project,but there is some problem.
Although it works in the functions of the other already defined functions of project,but it doesnt seem to work as a seperate function.So as title says,do i need to add my new function to somewhere in .h or .cpp files? I declared it in drawings.py

**Comment by leryss** [comment]
Make a copy of base_script.py and check other scripts how to implement those functions, also remove "target_champion": "none" line.

**Comment by rootcause0** [comment]
Alright,I've solved my issue thanks for your help.
PR is open.
